[env]
PROJECT_EXECUTE = "README.md"
PROJECT_SECTION = "Tasks"
_.python.venv = {path = ".venv", create = true}

[hooks]
postinstall = ["uv sync --all-extras --upgrade"]

[settings]
experimental = true
python.compile = true
python.uv_venv_auto = true

[tools]
ruff = "latest"
uv = "latest"
