[black]
line-length = 89
target-version = 'py310'

[mypy]
ignore_missing_imports = true

[ruff]
extend = "lint/ruff.toml"

[uv]
index-strategy = "unsafe-best-match"
package = true

[setuptools.package-dir]
"" = "src"
