[tool.flakeheaven]
docstring-convention = "google"
exclude = ["*.rst"]
format = "grouped"
max_line_length = 89
show_source = true

[tool.flakeheaven.plugins]
# flake8-variables-names = ['VNE001']
dlint = ["+*", '-DUO102', '-DUO130', '-DUO103']
flake8-aaa = ["+*", '-AAA01', '-AAA03', '-AAA04']
# flake8-annotations = ["+*"]
# flake8-annotations-complexity = ["+*"]
flake8-bugbear = ["+*"]
flake8-comprehensions = ["+*"]
flake8-debugger = ["+*"]
# flake8-docstrings = ["+*"]
flake8-eradicate = ["+*", '-E800']
flake8-expression-complexity = ["+*", '-ECE001']
flake8-fixme = ["+*", '-T101']
flake8-mutable = ["+*"]
flake8-pytest = ["+*"]
flake8-pytest-style = ["+*"]
flake8-simplify = ["+*"]
flake8-typing-imports = [
  "+*",
  "-TYP001",  # guard import by `if False:  # TYPE_CHECKING`: TYPE_CHECKING (not in
  "-TYP002"  # @overload is broken in <3.5.2, but we don't support Python 3.5
]
flake8-use-fstring = [
  "+*",
  '-FS002',  # force use f-string instead .format
  '-FS003'  # f-string missing prefix
]
mccabe = ["+*"]
pep8-naming = ["+*", '-N805', '-N812']
pycodestyle = [
  "+*",
  "-W503",  # No longer applies, incompatible with newer version of PEP8
  "-E704",  # Black collapses implementations of classes/functions consisting solely of ...
  "-E302",
  '-E265',
  '-E122',  # continuation line missing indentation or outdented
  '-E124',  # closing bracket does not match visual indentation
  '-E128',  # continuation line under-indented for visual indent
  '-E203',  # whitespace before ':'
  '-E221',  # multiple spaces before operator
  '-E225',  # missing whitespace around operator (i -1)
  '-E251',  # unexpected spaces around keyword / parameter equals
  '-E501',  # line too long (101 > 89 characters)
  '-W504'  # line break after binary operator
]
pyflakes = [
  "+*",
  '-F401',
  "-F841",  # Unused variable, already covered by W0612 of pylint
  "-F821"  # Undefined variable, already covered by E0602 of pylint
]
pylint = [
  "+*",
  "-C0411",  # %s should be placed before %s,
  "-R0903",  # Too few methods warning, but if you define an interface with just one
  "-W1203",  # Use %s formatting in logging functions. Deprecated rule in favor of
  "-W1201",  # Use lazy % formatting in logging functions. Deprecated rule in favor of
  "-C0301"  # Lines too long. Already covered by E501.
]
