exclude = [
  "__pycache__",
  ".git",
  "docs/conf.py"
]
fix = true
line-length = 89
output-format = "full"
target-version = "py310"

[lint]
extend = "lint/lint.toml"

[per-file-ignores]
"tests/*" = ["S101", "PLR2004", "ERA001", "INP001"]
