[lint.pycodestyle]
ignore-overlong-task-comments = true
max-doc-length = 89

[tool.black]
line-length = 89
target-version = 'py310'

[tool.ruff]
exclude = [
  "docs/conf.py"
]
extend = "pyproject.global.toml"
fix = true
line-length = 89
output-format = "full"
target-version = "py310"
lint.extend-ignore = [
  "G004"
]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101", "PLR2004", "ERA001", "INP001"]
